num1=input("Enter first number: ")
num2=input("Enter second number: ")
resultadd=int(num1)+int(num2)
resultsub=int(num1)-int(num2)
resultmul=int(num1)*int(num2)
resultdiv=float(num1)/float(num2)
print("Addition of two numbers is: "+str(resultadd))
print("Subtraction of two numbers is: "+str(resultsub))
print("Multiplication of two numbers is: "+str(resultmul))
print("Division of two numbers is: "+str(resultdiv))